### ISSUE TITLE
[Tock_docker_demo_api_webhook] SLF4J trouble

### ISSUE THREAD

**Issue by djowalker** [theopenconversationkit/tock-docker#25]
When launching it locally the logs shows : 

```SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It is due to upgrade of SLF4J to +2.X.
The pom depdencies of this project must be updated

**Comment by vsct-jburet** [comment]
launched in Intellij or in docker? (and then, which docker-compose) ?

**Comment by djowalker** [comment]
As i remmeber it was with docker-compose, i think : `docker-compose-bot-webhook.yml`
