### ISSUE TITLE
[Enhancement] Reduce docker images size

### ISSUE THREAD

**Issue by djowalker** [theopenconversationkit/tock-docker#30]
A fast little way to reduce ~100Mo image size is to use : 
amazoncorreto:$version-alpine instead of the full jdk.

Could be insteresting for all images.
I tried locally only on the bot_admin image locally but i think it could be possible to use this on all modules.

When i used that i manage to have this kind of difference on amazoncorreto:17 vs amazoncorreto:17-alpine as a base image.
```
#with amazoncorreto:17 : bot-admin      (...)     564MB 
#with amazoncorreto:17-alpine : bot-admin (...) 440MB
```

**Comment by vsct-jburet** [comment]
this is fixed :)
