### ISSUE TITLE
Gen-Ai Orchestrator - Release not build for linux/amd64

### ISSUE THREAD

**Issue by Benvii** [theopenconversationkit/tock-docker#39]
Hi,
I noticed that the latest release of `tock/gen-ai-orchestrator-server` available on Docker Hub, isn't build for **linux/amd64** only for **linux/arm64/v8** : 
![image](https://github.com/theopenconversationkit/tock-docker/assets/1092728/c6557d80-5cae-4c83-ae85-1772d1ef3790)

Latest snapshot is ok :
![image](https://github.com/theopenconversationkit/tock-docker/assets/1092728/c50bdd5d-7b6f-4c3e-870d-e4cb6bdc3fb4)

Reported thanks to @msansen-esncf

**Comment by vsct-jburet** [comment]
fixed
